// AUTO-GENERATED from packages/design-tokens/src/schema.ts — do not edit by hand.
// TODO(design): values are neutral placeholders pending the Aqualeo design system.
import Foundation

/// Namespaced design tokens, mirroring packages/design-tokens/src/schema.ts.
/// Native screens reference these by name — never hardcode visual values.
public enum DesignTokens {
    enum Color {
        /// TODO(design): placeholder. Token: "color.primary"
        static let primary = "#808080"
        /// TODO(design): placeholder. Token: "color.primary-foreground"
        static let primaryForeground = "#ffffff"
        /// TODO(design): placeholder. Token: "color.secondary"
        static let secondary = "#a0a0a0"
        /// TODO(design): placeholder. Token: "color.secondary-foreground"
        static let secondaryForeground = "#ffffff"
        /// TODO(design): placeholder. Token: "color.background"
        static let background = "#ffffff"
        /// TODO(design): placeholder. Token: "color.foreground"
        static let foreground = "#1a1a1a"
        /// TODO(design): placeholder. Token: "color.muted"
        static let muted = "#e0e0e0"
        /// TODO(design): placeholder. Token: "color.muted-foreground"
        static let mutedForeground = "#5a5a5a"
        /// TODO(design): placeholder. Token: "color.accent"
        static let accent = "#c0c0c0"
        /// TODO(design): placeholder. Token: "color.accent-foreground"
        static let accentForeground = "#1a1a1a"
        /// TODO(design): placeholder. Token: "color.destructive"
        static let destructive = "#b00020"
        /// TODO(design): placeholder. Token: "color.destructive-foreground"
        static let destructiveForeground = "#ffffff"
        /// TODO(design): placeholder. Token: "color.border"
        static let border = "#d0d0d0"
        /// TODO(design): placeholder. Token: "color.ring"
        static let ring = "#808080"
        /// TODO(design): placeholder. Token: "color.auspicious"
        static let auspicious = "#808080"
        /// TODO(design): placeholder. Token: "color.inauspicious"
        static let inauspicious = "#808080"
    }
    enum Typography {
        /// TODO(design): placeholder. Token: "typography.font-family-base"
        static let fontFamilyBase = "system-ui, sans-serif"
        /// TODO(design): placeholder. Token: "typography.font-family-display"
        static let fontFamilyDisplay = "system-ui, sans-serif"
        /// TODO(design): placeholder. Token: "typography.font-family-devanagari"
        static let fontFamilyDevanagari = "system-ui, sans-serif"
        /// TODO(design): placeholder. Token: "typography.weight-regular"
        static let weightRegular = "400"
        /// TODO(design): placeholder. Token: "typography.weight-medium"
        static let weightMedium = "500"
        /// TODO(design): placeholder. Token: "typography.weight-bold"
        static let weightBold = "700"
        /// TODO(design): placeholder. Token: "typography.scale-xs"
        static let scaleXs = "0.75rem"
        /// TODO(design): placeholder. Token: "typography.scale-sm"
        static let scaleSm = "0.875rem"
        /// TODO(design): placeholder. Token: "typography.scale-base"
        static let scaleBase = "1rem"
        /// TODO(design): placeholder. Token: "typography.scale-lg"
        static let scaleLg = "1.125rem"
        /// TODO(design): placeholder. Token: "typography.scale-xl"
        static let scaleXl = "1.25rem"
        /// TODO(design): placeholder. Token: "typography.scale-2xl"
        static let scale2xl = "1.5rem"
        /// TODO(design): placeholder. Token: "typography.scale-3xl"
        static let scale3xl = "1.875rem"
        /// TODO(design): placeholder. Token: "typography.leading-tight"
        static let leadingTight = "1.2"
        /// TODO(design): placeholder. Token: "typography.leading-normal"
        static let leadingNormal = "1.5"
        /// TODO(design): placeholder. Token: "typography.leading-relaxed"
        static let leadingRelaxed = "1.75"
    }
    enum Spacing {
        /// TODO(design): placeholder. Token: "spacing.xs"
        static let xs = "0.25rem"
        /// TODO(design): placeholder. Token: "spacing.sm"
        static let sm = "0.5rem"
        /// TODO(design): placeholder. Token: "spacing.md"
        static let md = "1rem"
        /// TODO(design): placeholder. Token: "spacing.lg"
        static let lg = "1.5rem"
        /// TODO(design): placeholder. Token: "spacing.xl"
        static let xl = "2rem"
        /// TODO(design): placeholder. Token: "spacing.2xl"
        static let 2xl = "3rem"
    }
    enum Radius {
        /// TODO(design): placeholder. Token: "radius.sm"
        static let sm = "0.125rem"
        /// TODO(design): placeholder. Token: "radius.md"
        static let md = "0.25rem"
        /// TODO(design): placeholder. Token: "radius.lg"
        static let lg = "0.5rem"
        /// TODO(design): placeholder. Token: "radius.full"
        static let full = "9999px"
    }
    enum Shadow {
        /// TODO(design): placeholder. Token: "shadow.sm"
        static let sm = "0 1px 2px rgba(0,0,0,0.08)"
        /// TODO(design): placeholder. Token: "shadow.md"
        static let md = "0 2px 6px rgba(0,0,0,0.10)"
        /// TODO(design): placeholder. Token: "shadow.lg"
        static let lg = "0 6px 16px rgba(0,0,0,0.12)"
    }
    enum Motion {
        /// TODO(design): placeholder. Token: "motion.duration-fast"
        static let durationFast = "100ms"
        /// TODO(design): placeholder. Token: "motion.duration-base"
        static let durationBase = "200ms"
        /// TODO(design): placeholder. Token: "motion.duration-slow"
        static let durationSlow = "320ms"
        /// TODO(design): placeholder. Token: "motion.easing-standard"
        static let easingStandard = "cubic-bezier(0.2, 0, 0, 1)"
        /// TODO(design): placeholder. Token: "motion.easing-decelerate"
        static let easingDecelerate = "cubic-bezier(0, 0, 0, 1)"
        /// TODO(design): placeholder. Token: "motion.easing-accelerate"
        static let easingAccelerate = "cubic-bezier(0.3, 0, 1, 1)"
    }
    enum ZIndex {
        /// TODO(design): placeholder. Token: "zIndex.base"
        static let base = "0"
        /// TODO(design): placeholder. Token: "zIndex.dropdown"
        static let dropdown = "1000"
        /// TODO(design): placeholder. Token: "zIndex.sticky"
        static let sticky = "1100"
        /// TODO(design): placeholder. Token: "zIndex.overlay"
        static let overlay = "1200"
        /// TODO(design): placeholder. Token: "zIndex.modal"
        static let modal = "1300"
        /// TODO(design): placeholder. Token: "zIndex.toast"
        static let toast = "1400"
    }
    enum Breakpoint {
        /// TODO(design): placeholder. Token: "breakpoint.sm"
        static let sm = "640px"
        /// TODO(design): placeholder. Token: "breakpoint.md"
        static let md = "768px"
        /// TODO(design): placeholder. Token: "breakpoint.lg"
        static let lg = "1024px"
        /// TODO(design): placeholder. Token: "breakpoint.xl"
        static let xl = "1280px"
        /// TODO(design): placeholder. Token: "breakpoint.2xl"
        static let 2xl = "1536px"
    }
}
